# Generated by Django 4.2.5 on 2023-10-03 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_alter_epic_last_edited_alter_epic_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='last_edited',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 15, 55, 21, 644615)),
        ),
        migrations.AlterField(
            model_name='epic',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 15, 55, 21, 644615)),
        ),
        migrations.AlterField(
            model_name='story',
            name='last_edited',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 15, 55, 21, 644615)),
        ),
        migrations.AlterField(
            model_name='story',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 15, 55, 21, 644615)),
        ),
    ]
