# Generated by Django 4.2.5 on 2023-10-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_alter_epic_last_edited_alter_epic_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='epic_colour',
            field=models.CharField(default='#3fd9cc', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='last_edited',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='story',
            name='time_created',
            field=models.CharField(max_length=128),
        ),
    ]
