# Generated by Django 4.2.5 on 2023-10-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_epic_epic_colour_alter_story_last_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='epic_colour',
            field=models.CharField(max_length=20),
        ),
    ]
