# Generated by Django 4.2.5 on 2023-10-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_remove_epic_epic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='epic_id',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
