# Generated by Django 4.2.5 on 2023-10-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_epic_epic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='epic',
            name='epic_colour',
            field=models.CharField(max_length=6),
        ),
    ]
