# Generated by Django 4.2.5 on 2023-10-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_story_order_alter_epic_epic_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
