# Generated by Django 4.2.5 on 2023-10-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0011_epic_order_alter_story_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
