# Generated by Django 4.2.5 on 2023-10-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0012_alter_epic_order_alter_story_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='order',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='story',
            name='order',
            field=models.IntegerField(default=-1),
        ),
    ]
