# Generated by Django 4.2.5 on 2023-10-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0014_tag_epic_tags_story_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_id',
            field=models.CharField(default='error', max_length=8),
        ),
    ]
