# Generated by Django 4.2.5 on 2023-10-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0015_tag_tag_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='team_id',
            field=models.CharField(default='error', max_length=8),
        ),
    ]
