# Generated by Django 4.2.5 on 2023-11-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0016_tag_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='tags',
            field=models.ManyToManyField(blank=True, to='web_app.tag'),
        ),
        migrations.AlterField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(blank=True, to='web_app.tag'),
        ),
        migrations.RemoveField(
            model_name='story',
            name='values',
        ),
        migrations.CreateModel(
            name='ValueTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(default='error', max_length=8)),
                ('team_id', models.CharField(default='error', max_length=8)),
                ('title', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=128)),
                ('colour', models.CharField(max_length=6)),
                ('sub_values', models.ManyToManyField(blank=True, null=True, to='web_app.valuetag')),
            ],
        ),
        migrations.AddField(
            model_name='epic',
            name='values',
            field=models.ManyToManyField(blank=True, to='web_app.valuetag'),
        ),
        migrations.AddField(
            model_name='story',
            name='values',
            field=models.ManyToManyField(blank=True, to='web_app.valuetag'),
        ),
    ]
