# Generated by Django 4.2.5 on 2023-11-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0019_story_state_story_story_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_id', models.CharField(default='error', max_length=8)),
                ('dashboard_id', models.CharField(default='error', max_length=8)),
                ('team_id', models.CharField(default='error', max_length=8)),
                ('title', models.CharField(max_length=30)),
                ('mark_as_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='valuetag',
            name='sub_values',
            field=models.ManyToManyField(blank=True, default=[], to='web_app.valuetag'),
        ),
        migrations.AlterField(
            model_name='valuetag',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
