# Generated by Django 4.2.5 on 2023-11-29 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0021_trackingcolumn_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='state',
            field=models.CharField(default='undefined', max_length=128),
        ),
        migrations.RemoveField(
            model_name='trackingcolumn',
            name='stories',
        ),
        migrations.AddField(
            model_name='trackingcolumn',
            name='stories',
            field=models.ManyToManyField(blank=True, default=[], to='web_app.story'),
        ),
    ]
