# Generated by Django 4.2.5 on 2023-11-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0024_alter_trackingcolumn_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingcolumn',
            name='stories',
            field=models.ManyToManyField(blank=True, to='web_app.story'),
        ),
    ]
