# Generated by Django 4.2.5 on 2023-11-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0025_alter_trackingcolumn_stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingcolumn',
            name='story_list',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='trackingcolumn',
            name='stories',
            field=models.ManyToManyField(blank=True, default=[], to='web_app.story'),
        ),
    ]
