# Generated by Django 4.2.5 on 2023-12-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0028_alter_trackingcolumn_wip_sprint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='epic',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.CharField(default='error', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.CharField(default='error', max_length=1024),
        ),
        migrations.AlterField(
            model_name='story',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='story',
            name='definition_of_done',
            field=models.CharField(blank=True, max_length=1028),
        ),
        migrations.AlterField(
            model_name='story',
            name='pairable',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='user_story',
            field=models.CharField(blank=True, max_length=1028),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='trackingcolumn',
            name='WIP',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='valuetag',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
