# Generated by Django 4.2.5 on 2024-01-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0029_delete_task_epic_completed_story_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='error', max_length=32, unique=True)),
                ('first_name', models.CharField(default='error', max_length=128)),
                ('surname_name', models.CharField(default='error', max_length=128)),
                ('role', models.CharField(default='error', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='error', max_length=32)),
                ('picture', models.ImageField(upload_to='')),
                ('team_members', models.ManyToManyField(blank=True, to='web_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_id', models.CharField(default='error', max_length=8)),
                ('name', models.CharField(default='error', max_length=128)),
                ('admins', models.ManyToManyField(blank=True, to='web_app.user')),
                ('teams', models.ManyToManyField(blank=True, to='web_app.team')),
            ],
        ),
    ]
