# Generated by Django 4.2.5 on 2024-01-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0030_user_team_organisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='surname_name',
            new_name='surname',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='organisation_id',
        ),
    ]
