# Generated by Django 4.2.5 on 2024-01-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0031_rename_surname_name_user_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(blank=True, to='web_app.team'),
        ),
    ]
