# Generated by Django 4.2.5 on 2024-01-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0032_user_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='admins',
            new_name='users',
        ),
    ]
