# Generated by Django 4.2.5 on 2024-01-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0033_rename_admins_organisation_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='belongs_to',
            field=models.ManyToManyField(blank=True, to='web_app.organisation'),
        ),
    ]
