# Generated by Django 4.2.5 on 2024-01-08 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0034_user_belongs_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='belongs_to',
        ),
        migrations.AddField(
            model_name='user',
            name='belongs_to',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='web_app.organisation'),
            preserve_default=False,
        ),
    ]
