# Generated by Django 4.2.5 on 2024-01-14 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0035_remove_user_belongs_to_user_belongs_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team_name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='picture',
            new_name='team_photo',
        ),
        migrations.AddField(
            model_name='team',
            name='team_leads',
            field=models.ManyToManyField(blank=True, related_name='team_leads', to='web_app.user'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team_members', to='web_app.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.organisation'),
        ),
    ]
