# Generated by Django 4.2.5 on 2024-01-14 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0036_rename_name_team_team_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.organisation'),
        ),
    ]
