# Generated by Django 4.2.5 on 2024-01-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0037_team_belongs_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_photo',
            field=models.CharField(default='error', max_length=1024),
        ),
    ]
