# Generated by Django 4.2.5 on 2024-01-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0039_alter_team_team_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.CharField(default='error', max_length=1024),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_photo',
            field=models.CharField(default='error', max_length=1024),
        ),
    ]
