# Generated by Django 4.2.5 on 2024-01-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0040_user_profile_photo_alter_team_team_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_photo',
            field=models.ImageField(blank=True, upload_to='team_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
