# Generated by Django 4.2.5 on 2024-01-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0043_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='story',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, to='web_app.user'),
        ),
    ]
