# Generated by Django 4.2.5 on 2024-01-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0044_remove_story_assigned_to_story_assigned_to'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
